### ISSUE TITLE
Map has no Layers property

### ISSUE THREAD

**Issue by erikthysell** [Mehigh17/BlazorLeaflet#19]
In `LeafletMap.razor` `Map.Layers` does not exist. (it seems that it should just be the property encapsulating `private ObservableCollection<Layer> _layers` in `Map.cs`.

**Comment by Mehigh17** [comment]
Hello, recently the master branch has been became the main development branch and the readme has not been updated. Please use the latest tag in order to use the API as described in the readme.

**Comment by erikthysell** [comment]
Sorry, I am a total newbie but how exactly should I "use the latest tag" ?
