### ISSUE TITLE
Zoom on an area of the map

### ISSUE THREAD

**Issue by sylvainonweb** [Mehigh17/BlazorLeaflet#3]
Hi, 

On my map, I have some markers and would like to be able to zoom on these markers.
To do it, I tried to :
* retrieve all the markers
* find the coordinates of the box around all markers (min x, min y, max x, max y)
* call a fitBounds method I created in leafletBlazorInterops.js
```
    fitBounds: function (mapId, minX, minY, maxX, maxY) {
        var corner1 = new L.LatLng(maxX, minY);
        var corner2 = new L.LatLng(minX, maxY);
        var bounds = new L.LatLngBounds(corner1, corner2);
        maps[mapId].fitBounds(bounds, { padding: [50, 50] });
    }

If I add a button to call this method, all is ok but I I call this method in OnInitialized, nothing is done.

Could you help me on this point ?


```

**Comment by Mehigh17** [comment]
Hello,

This function has been added to the newest version 0.3.0-alpha that I will release soon. You just have to call "map.FitBounds(p1, p2)".
