### ISSUE TITLE
Clear() on Map.Layers doesn't remove layers from DOM

### ISSUE THREAD

**Issue by sylvainonweb** [Mehigh17/BlazorLeaflet#4]
Hi,

Because Map.Layers.Clears() raise a Reset event and the OnLayersChanged(object sender, NotifyCollectionChangedEventArgs args) method doesn't process it (it actually can't because items aren't anymore in the collection), the items aren't removed from the DOM.

One solution would be to create a Layers class which redefine the Clear() method like this :

  ```
public class Layers : ObservableCollection<Layer>
    {
        public new void Clear()
        {
            for (int i = this.Items.Count - 1; i >= 0; i--)
            {
                this.Remove(this.Items[i]);
            }
        }
    }
```

Perhaps you will find a better solution.

**Comment by Mehigh17** [comment]
Hello.

I have fixed this in the version 0.3.0-alpha. I think it's more pertinent to add a clear method on the client side rather than sending a new packet for every single frame for each layer to remove.
