### ISSUE TITLE
Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by sylvainonweb** [Mehigh17/BlazorLeaflet#5]
In some cases (I can't reproduce it with your sample), the OnAfterRenderAsync method throws the following exception "Collection was modified; enumeration operation may not execute".
It seems to be because when the loop is adding the layers to the DOM, some other layers are added to the collection, thing that is not authorized.

This is probably due to the fact that I use OnParametersSet (and not OnInitialized) to add layers (because I need to) and that OnParametersSet is not called only one time.

I can fix this issue adding a ToList() to the loop like this.

```
 protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await LeafletInterops.Create(JsRuntime, Map.Id, InitialPosition, InitialZoom);

            Map.Layers.CollectionChanged += OnLayersChanged;
            foreach (var layer in Map.Layers.**ToList**())
            {
                await LeafletInterops.AddLayer(JsRuntime, Map.Id, layer);
            }
        }
    }
```

**Comment by Mehigh17** [comment]
Indeed, I haven't thought of this case. Calling .ToList() on the collection creates a different list from the source one preventing this, so I guess it can be a fix. Will be fixed in 0.3.0-alpha.
Thanks!
