### ISSUE TITLE
ReferenceError: L is not defined (WASM)

### ISSUE THREAD

**Issue by johannesmols** [Mehigh17/BlazorLeaflet#50]
I'm trying to get this to work using WebAssembly, but keep getting "ReferenceError: L is not defined" in the leafletBlazorInterops.js file.

I added the script to the index.html file, and my component looks like this:
```
@page "/graphs"
@inject IJSRuntime jsRuntime

<div id="mapContainer" style="width: 300px; height: 300px">
    <LeafletMap Map="_map" />
</div>

@code {
    private Map _map;

    protected override void OnInitialized()
    {
        _map = new Map(jsRuntime);
    }
}
```

What am I doing wrong? The sample project runs fine for me but I can't find any difference except that I am using WebAssembly.

**Comment by dvv153m** [comment]
In index.html add:
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
            integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
            crossorigin=""></script>

**Comment by johannesmols** [comment]
I did that but it has no effect.

**Comment by dvv153m** [comment]
Strange, it works for me, https://github.com/dvv153m/BlazorMap

**Comment by Kohlroulade** [comment]
Worked for me. However The map-div is empty

**Comment by johannesmols** [comment]
This is really strange. I actually didn't add the script like you explained and that removed the error. However, when I run the project it does load the frame and map controls, but there is no map. It is just grey.

I downloaded your example @dvv153m and that works perfectly. I can't find a single difference between yours and mine... Could the issue be that we have to download the library manually because the last release is so outdated? Even though the package versions between mine and yours are also exactly the same. I'm really at a loss what the problem here is.

**Comment by johannesmols** [comment]
I managed to make it work now. Apparently the attribution layer is required and it will be grey if it isn't added. I could swear I had it in before and it didn't work but maybe I'm just imagining that. Anyway, thanks for your help.

**Comment by astrowalker** [comment]
For other facing also the case "I did that but it has no effect." :-) -- the browser can cache the code, so even after the changes you will see the old code in action. Reload page to really see the actual code in action.
